
version: '3.7'
services:
    page:
        image: jekyll/jekyll:3.8.5
        volumes: 
            - ./:/srv/jekyll
        ports: 
            - 4000:4000
            - 35729:35729
        command: jekyll serve --livereload