version: '3.7'
services:
  page:
    image: jekyll/jekyll:pages
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
    command: bash -c "jekyll clean && jekyll serve --watch"
