name: Update projects data

on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12.15 
    - run: cd data-loaders 
    - run: npm install
    - run: node project-fetcher.js
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
